/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMailRouteImport } from './routes/_app/mail'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppContentIndexRouteImport } from './routes/_app/content.index'
import { Route as AppContentMediaRouteImport } from './routes/_app/content.media'
import { Route as AppMailIndexRouteImport } from './routes/_app/mail.index'
import { Route as AppMailThreadIdRouteImport } from './routes/_app/mail.$threadId'
import { Route as AppMailSettingsRouteImport } from './routes/_app/mail.settings'
import { Route as AppSettingsMailRouteImport } from './routes/_app/settings.mail'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings.members'
import { Route as AppSettingsSiteRouteImport } from './routes/_app/settings.site'
import { Route as ApiResendInboundRouteImport } from './routes/api/resend/inbound'
import { Route as AppContentCollectionsKeyRouteImport } from './routes/_app/content.collections.$key'
import { Route as AppContentPagesSlugRouteImport } from './routes/_app/content.pages.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentMediaRoute = AppContentMediaRouteImport.update({
  id: '/content/media',
  path: '/content/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMailIndexRoute = AppMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailThreadIdRoute = AppMailThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailSettingsRoute = AppMailSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMailRoute,
} as any)
const AppSettingsMailRoute = AppSettingsMailRouteImport.update({
  id: '/settings/mail',
  path: '/settings/mail',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSiteRoute = AppSettingsSiteRouteImport.update({
  id: '/settings/site',
  path: '/settings/site',
  getParentRoute: () => AppRoute,
} as any)
const ApiResendInboundRoute = ApiResendInboundRouteImport.update({
  id: '/api/resend/inbound',
  path: '/api/resend/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContentCollectionsKeyRoute =
  AppContentCollectionsKeyRouteImport.update({
    id: '/content/collections/$key',
    path: '/content/collections/$key',
    getParentRoute: () => AppRoute,
  } as any)
const AppContentPagesSlugRoute = AppContentPagesSlugRouteImport.update({
  id: '/content/pages/$slug',
  path: '/content/pages/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mail': typeof AppMailRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/content/media': typeof AppContentMediaRoute
  '/mail/$threadId': typeof AppMailThreadIdRoute
  '/mail/settings': typeof AppMailSettingsRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/site': typeof AppSettingsSiteRoute
  '/api/resend/inbound': typeof ApiResendInboundRoute
  '/content/': typeof AppContentIndexRoute
  '/mail/': typeof AppMailIndexRoute
  '/content/collections/$key': typeof AppContentCollectionsKeyRoute
  '/content/pages/$slug': typeof AppContentPagesSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/content/media': typeof AppContentMediaRoute
  '/mail/$threadId': typeof AppMailThreadIdRoute
  '/mail/settings': typeof AppMailSettingsRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/site': typeof AppSettingsSiteRoute
  '/api/resend/inbound': typeof ApiResendInboundRoute
  '/content': typeof AppContentIndexRoute
  '/mail': typeof AppMailIndexRoute
  '/content/collections/$key': typeof AppContentCollectionsKeyRoute
  '/content/pages/$slug': typeof AppContentPagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/mail': typeof AppMailRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/content/media': typeof AppContentMediaRoute
  '/_app/mail/$threadId': typeof AppMailThreadIdRoute
  '/_app/mail/settings': typeof AppMailSettingsRoute
  '/_app/settings/mail': typeof AppSettingsMailRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/site': typeof AppSettingsSiteRoute
  '/api/resend/inbound': typeof ApiResendInboundRoute
  '/_app/content/': typeof AppContentIndexRoute
  '/_app/mail/': typeof AppMailIndexRoute
  '/_app/content/collections/$key': typeof AppContentCollectionsKeyRoute
  '/_app/content/pages/$slug': typeof AppContentPagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mail'
    | '/profile'
    | '/content/media'
    | '/mail/$threadId'
    | '/mail/settings'
    | '/settings/mail'
    | '/settings/members'
    | '/settings/site'
    | '/api/resend/inbound'
    | '/content/'
    | '/mail/'
    | '/content/collections/$key'
    | '/content/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/content/media'
    | '/mail/$threadId'
    | '/mail/settings'
    | '/settings/mail'
    | '/settings/members'
    | '/settings/site'
    | '/api/resend/inbound'
    | '/content'
    | '/mail'
    | '/content/collections/$key'
    | '/content/pages/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/mail'
    | '/_app/profile'
    | '/_app/'
    | '/_app/content/media'
    | '/_app/mail/$threadId'
    | '/_app/mail/settings'
    | '/_app/settings/mail'
    | '/_app/settings/members'
    | '/_app/settings/site'
    | '/api/resend/inbound'
    | '/_app/content/'
    | '/_app/mail/'
    | '/_app/content/collections/$key'
    | '/_app/content/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiResendInboundRoute: typeof ApiResendInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail': {
      id: '/_app/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/': {
      id: '/_app/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/media': {
      id: '/_app/content/media'
      path: '/content/media'
      fullPath: '/content/media'
      preLoaderRoute: typeof AppContentMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mail/': {
      id: '/_app/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof AppMailIndexRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/$threadId': {
      id: '/_app/mail/$threadId'
      path: '/$threadId'
      fullPath: '/mail/$threadId'
      preLoaderRoute: typeof AppMailThreadIdRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/mail/settings': {
      id: '/_app/mail/settings'
      path: '/settings'
      fullPath: '/mail/settings'
      preLoaderRoute: typeof AppMailSettingsRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/settings/mail': {
      id: '/_app/settings/mail'
      path: '/settings/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof AppSettingsMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/site': {
      id: '/_app/settings/site'
      path: '/settings/site'
      fullPath: '/settings/site'
      preLoaderRoute: typeof AppSettingsSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/resend/inbound': {
      id: '/api/resend/inbound'
      path: '/api/resend/inbound'
      fullPath: '/api/resend/inbound'
      preLoaderRoute: typeof ApiResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/content/collections/$key': {
      id: '/_app/content/collections/$key'
      path: '/content/collections/$key'
      fullPath: '/content/collections/$key'
      preLoaderRoute: typeof AppContentCollectionsKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/pages/$slug': {
      id: '/_app/content/pages/$slug'
      path: '/content/pages/$slug'
      fullPath: '/content/pages/$slug'
      preLoaderRoute: typeof AppContentPagesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMailRouteChildren {
  AppMailThreadIdRoute: typeof AppMailThreadIdRoute
  AppMailSettingsRoute: typeof AppMailSettingsRoute
  AppMailIndexRoute: typeof AppMailIndexRoute
}

const AppMailRouteChildren: AppMailRouteChildren = {
  AppMailThreadIdRoute: AppMailThreadIdRoute,
  AppMailSettingsRoute: AppMailSettingsRoute,
  AppMailIndexRoute: AppMailIndexRoute,
}

const AppMailRouteWithChildren =
  AppMailRoute._addFileChildren(AppMailRouteChildren)

interface AppRouteChildren {
  AppMailRoute: typeof AppMailRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContentMediaRoute: typeof AppContentMediaRoute
  AppSettingsMailRoute: typeof AppSettingsMailRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsSiteRoute: typeof AppSettingsSiteRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
  AppContentCollectionsKeyRoute: typeof AppContentCollectionsKeyRoute
  AppContentPagesSlugRoute: typeof AppContentPagesSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMailRoute: AppMailRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppContentMediaRoute: AppContentMediaRoute,
  AppSettingsMailRoute: AppSettingsMailRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsSiteRoute: AppSettingsSiteRoute,
  AppContentIndexRoute: AppContentIndexRoute,
  AppContentCollectionsKeyRoute: AppContentCollectionsKeyRoute,
  AppContentPagesSlugRoute: AppContentPagesSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiResendInboundRoute: ApiResendInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
